import type { Metadata } from "next";
import "./globals.css";
// import "react-multi-carousel/lib/styles.css";
// import "bootstrap/dist/js/bootstrap.js";
// import "aos/dist/aos.css";
// import "aos/dist/aos.js";
import "../assets/css/style.css";
import "../assets/css/countdown.css";
import "../assets/css/bootstrap.css";
import "../assets/fontawesome/css/all.css";
// import "./App.css";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import AllProviders from "./providers/AllProviders";
import CookiesComponent from "@/components/CookiesBanner/Cookies";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <AllProviders>
          <ToastContainer />
          {/* <Navbar /> */}
          <CookiesComponent />
          {children}
          <Analytics />
          <SpeedInsights />
          <Footer />
        </AllProviders>
        <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
        <script src="../assets/js/bootstrap.bundle.min.js"></script>
        <script src="../assets/js/bootstrap.js"></script>
        <script src="../assets/js/main.js"></script>
        <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
      </body>
    </html>
  );
}
